version: '3.9'

services:
  frontend:
    build: ./frontend
    image: mrkiwi-frontend
    ports:
      - "3000:3000"
    restart: always

  backend:
    build: ./backend
    image: mrkiwi-backend
    ports:
      - "8080:8080"
    restart: always

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata: {}
    