version: '3.9'

services:
  frontend:
    build: ./frontend
    image: mrkiwi-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: always

  backend:
    build: ./backend
    image: mrkiwi-backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - /app/tmp
    env_file:
      - .env
    restart: always
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      # when dev use mock
      - ./backend/mockdata.sql:/docker-entrypoint-initdb.d/mockdata.sql:ro
      # when prod use init
      # - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: always

volumes:
  pgdata: {}
    